// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshSession struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	GoogleSubject string
	Email         string
	DisplayName   pgtype.Text
	AvatarUrl     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
