// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_sessions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshSession = `-- name: CreateRefreshSession :exec
INSERT INTO refresh_sessions (token_hash, user_id, expires_at)
VALUES ($1, $2::uuid, now() + interval '30 days')
`

type CreateRefreshSessionParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) error {
	_, err := q.db.Exec(ctx, createRefreshSession, arg.TokenHash, arg.UserID)
	return err
}

const deleteRefreshSession = `-- name: DeleteRefreshSession :exec
DELETE FROM refresh_sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteRefreshSession, tokenHash)
	return err
}

const rotateRefreshSession = `-- name: RotateRefreshSession :one
UPDATE refresh_sessions
SET token_hash = $1,
    expires_at = now() + interval '30 days'
WHERE token_hash = $2
  AND expires_at > now()
RETURNING user_id::text
`

type RotateRefreshSessionParams struct {
	NewTokenHash []byte
	OldTokenHash []byte
}

func (q *Queries) RotateRefreshSession(ctx context.Context, arg RotateRefreshSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, rotateRefreshSession, arg.NewTokenHash, arg.OldTokenHash)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
