// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultCategories = `-- name: CreateDefaultCategories :execrows
INSERT INTO categories (user_id, name, type, icon, color, is_default)
VALUES
    ($1::uuid, 'Salary', 'income', 'briefcase-business', '#16A34A', true),
    ($1::uuid, 'Freelance', 'income', 'laptop', '#0D9488', true),
    ($1::uuid, 'Investment', 'income', 'chart-no-axes-combined', '#2563EB', true),
    ($1::uuid, 'Other Income', 'income', 'circle-plus', '#7C3AED', true),
    ($1::uuid, 'Food & Dining', 'expense', 'utensils', '#EA580C', true),
    ($1::uuid, 'Transportation', 'expense', 'car', '#0891B2', true),
    ($1::uuid, 'Housing', 'expense', 'house', '#9333EA', true),
    ($1::uuid, 'Bills & Utilities', 'expense', 'receipt-text', '#CA8A04', true),
    ($1::uuid, 'Shopping', 'expense', 'shopping-bag', '#DB2777', true),
    ($1::uuid, 'Healthcare', 'expense', 'heart-pulse', '#DC2626', true),
    ($1::uuid, 'Entertainment', 'expense', 'gamepad-2', '#4F46E5', true),
    ($1::uuid, 'Other Expense', 'expense', 'circle-minus', '#64748B', true)
ON CONFLICT (user_id, type, lower(name)) DO NOTHING
`

func (q *Queries) CreateDefaultCategories(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, createDefaultCategories, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
