// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Type      string
	Icon      pgtype.Text
	Color     pgtype.Text
	IsDefault bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Wallet struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Type         string
	Balance      pgtype.Numeric
	CurrencyCode string
	IsDefault    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
