// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    category_id,
    wallet_id,
    type,
    amount,
    description,
    transaction_date
)
SELECT
    $1::uuid,
    category.id,
    wallet.id,
    $2,
    $3::text::numeric,
    NULLIF($4::text, ''),
    $5::date
FROM categories AS category
CROSS JOIN wallets AS wallet
WHERE category.id = $6::uuid
  AND category.user_id = $1::uuid
  AND category.type = $2
  AND wallet.id = $7::uuid
  AND wallet.user_id = $1::uuid
RETURNING id::text AS id, category_id::text AS category_id,
          wallet_id::text AS wallet_id, type, amount::text AS amount,
          description, transaction_date, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID          pgtype.UUID
	Type            string
	Amount          string
	Description     string
	TransactionDate pgtype.Date
	CategoryID      pgtype.UUID
	WalletID        pgtype.UUID
}

type CreateTransactionRow struct {
	ID              string
	CategoryID      string
	WalletID        string
	Type            string
	Amount          string
	Description     pgtype.Text
	TransactionDate pgtype.Date
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.TransactionDate,
		arg.CategoryID,
		arg.WalletID,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions
WHERE id = $1::uuid
  AND user_id = $2::uuid
`

type DeleteTransactionParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id::text AS id, category_id::text AS category_id,
       wallet_id::text AS wallet_id, type, amount::text AS amount,
       description, transaction_date, created_at, updated_at
FROM transactions
WHERE id = $1::uuid
  AND user_id = $2::uuid
`

type GetTransactionParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetTransactionRow struct {
	ID              string
	CategoryID      string
	WalletID        string
	Type            string
	Amount          string
	Description     pgtype.Text
	TransactionDate pgtype.Date
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id::text AS id, category_id::text AS category_id,
       wallet_id::text AS wallet_id, type, amount::text AS amount,
       description, transaction_date, created_at, updated_at
FROM transactions
WHERE user_id = $1::uuid
  AND (
      $2::date IS NULL
      OR (
          transaction_date >= $2::date
          AND transaction_date < $2::date + INTERVAL '1 month'
      )
  )
  AND ($3::text IS NULL OR type = $3::text)
ORDER BY transaction_date DESC, created_at DESC, id DESC
`

type ListTransactionsParams struct {
	UserID     pgtype.UUID
	MonthStart pgtype.Date
	Type       pgtype.Text
}

type ListTransactionsRow struct {
	ID              string
	CategoryID      string
	WalletID        string
	Type            string
	Amount          string
	Description     pgtype.Text
	TransactionDate pgtype.Date
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.UserID, arg.MonthStart, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.WalletID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions AS txn
SET
    category_id = COALESCE($1::uuid, txn.category_id),
    wallet_id = COALESCE($2::uuid, txn.wallet_id),
    type = COALESCE($3::text, txn.type),
    amount = COALESCE($4::text::numeric, txn.amount),
    description = CASE
        WHEN $5::boolean
            THEN NULLIF($6::text, '')
        ELSE txn.description
    END,
    transaction_date = COALESCE($7::date, txn.transaction_date),
    updated_at = now()
WHERE txn.id = $8::uuid
  AND txn.user_id = $9::uuid
  AND EXISTS (
      SELECT 1
      FROM categories AS category
      WHERE category.id = COALESCE($1::uuid, txn.category_id)
        AND category.user_id = txn.user_id
        AND category.type = COALESCE($3::text, txn.type)
  )
  AND EXISTS (
      SELECT 1
      FROM wallets AS wallet
      WHERE wallet.id = COALESCE($2::uuid, txn.wallet_id)
        AND wallet.user_id = txn.user_id
  )
RETURNING txn.id::text AS id,
          txn.category_id::text AS category_id,
          txn.wallet_id::text AS wallet_id,
          txn.type,
          txn.amount::text AS amount,
          txn.description,
          txn.transaction_date,
          txn.created_at,
          txn.updated_at
`

type UpdateTransactionParams struct {
	CategoryID      pgtype.UUID
	WalletID        pgtype.UUID
	Type            pgtype.Text
	Amount          pgtype.Text
	SetDescription  bool
	Description     pgtype.Text
	TransactionDate pgtype.Date
	ID              pgtype.UUID
	UserID          pgtype.UUID
}

type UpdateTransactionRow struct {
	ID              string
	CategoryID      string
	WalletID        string
	Type            string
	Amount          string
	Description     pgtype.Text
	TransactionDate pgtype.Date
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.CategoryID,
		arg.WalletID,
		arg.Type,
		arg.Amount,
		arg.SetDescription,
		arg.Description,
		arg.TransactionDate,
		arg.ID,
		arg.UserID,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
