// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultCashWallet = `-- name: CreateDefaultCashWallet :execrows
INSERT INTO wallets (user_id, name, type, balance, currency_code, is_default)
VALUES ($1::uuid, 'Cash', 'cash', 0, 'THB', true)
ON CONFLICT (user_id, lower(name)) DO NOTHING
`

func (q *Queries) CreateDefaultCashWallet(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, createDefaultCashWallet, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
