// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (user_id, category_id, amount, month_start)
SELECT
    $1::uuid,
    category.id,
    $2::text::numeric,
    $3::date
FROM categories AS category
WHERE category.id = $4::uuid
  AND category.user_id = $1::uuid
  AND category.type = 'expense'
RETURNING id::text AS id, category_id::text AS category_id,
          amount::text AS amount, month_start, created_at, updated_at
`

type CreateBudgetParams struct {
	UserID     pgtype.UUID
	Amount     string
	MonthStart pgtype.Date
	CategoryID pgtype.UUID
}

type CreateBudgetRow struct {
	ID         string
	CategoryID string
	Amount     string
	MonthStart pgtype.Date
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (CreateBudgetRow, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.UserID,
		arg.Amount,
		arg.MonthStart,
		arg.CategoryID,
	)
	var i CreateBudgetRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Amount,
		&i.MonthStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :execrows
DELETE FROM budgets
WHERE id = $1::uuid
  AND user_id = $2::uuid
`

type DeleteBudgetParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBudget, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBudget = `-- name: GetBudget :one
SELECT id::text AS id, category_id::text AS category_id,
       amount::text AS amount, month_start, created_at, updated_at
FROM budgets
WHERE id = $1::uuid
  AND user_id = $2::uuid
`

type GetBudgetParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetBudgetRow struct {
	ID         string
	CategoryID string
	Amount     string
	MonthStart pgtype.Date
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (GetBudgetRow, error) {
	row := q.db.QueryRow(ctx, getBudget, arg.ID, arg.UserID)
	var i GetBudgetRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Amount,
		&i.MonthStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT id::text AS id, category_id::text AS category_id,
       amount::text AS amount, month_start, created_at, updated_at
FROM budgets
WHERE user_id = $1::uuid
  AND ($2::date IS NULL OR month_start = $2::date)
ORDER BY month_start DESC, created_at DESC, id DESC
`

type ListBudgetsParams struct {
	UserID     pgtype.UUID
	MonthStart pgtype.Date
}

type ListBudgetsRow struct {
	ID         string
	CategoryID string
	Amount     string
	MonthStart pgtype.Date
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListBudgets(ctx context.Context, arg ListBudgetsParams) ([]ListBudgetsRow, error) {
	rows, err := q.db.Query(ctx, listBudgets, arg.UserID, arg.MonthStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetsRow
	for rows.Next() {
		var i ListBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Amount,
			&i.MonthStart,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets AS budget
SET
    category_id = COALESCE($1::uuid, budget.category_id),
    amount = COALESCE($2::text::numeric, budget.amount),
    month_start = COALESCE($3::date, budget.month_start),
    updated_at = now()
WHERE budget.id = $4::uuid
  AND budget.user_id = $5::uuid
  AND EXISTS (
      SELECT 1
      FROM categories AS category
      WHERE category.id = COALESCE($1::uuid, budget.category_id)
        AND category.user_id = budget.user_id
        AND category.type = 'expense'
  )
RETURNING budget.id::text AS id,
          budget.category_id::text AS category_id,
          budget.amount::text AS amount,
          budget.month_start,
          budget.created_at,
          budget.updated_at
`

type UpdateBudgetParams struct {
	CategoryID pgtype.UUID
	Amount     pgtype.Text
	MonthStart pgtype.Date
	ID         pgtype.UUID
	UserID     pgtype.UUID
}

type UpdateBudgetRow struct {
	ID         string
	CategoryID string
	Amount     string
	MonthStart pgtype.Date
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (UpdateBudgetRow, error) {
	row := q.db.QueryRow(ctx, updateBudget,
		arg.CategoryID,
		arg.Amount,
		arg.MonthStart,
		arg.ID,
		arg.UserID,
	)
	var i UpdateBudgetRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Amount,
		&i.MonthStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
