// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id::text AS id, email,
       COALESCE(display_name, '')::text AS display_name,
       COALESCE(avatar_url, '')::text AS avatar_url
FROM users
WHERE id = $1::uuid
`

type GetUserByIDRow struct {
	ID          string
	Email       string
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const upsertGoogleUser = `-- name: UpsertGoogleUser :one
INSERT INTO users (google_subject, email, display_name, avatar_url)
VALUES (
    $1,
    $2,
    NULLIF($3::text, ''),
    NULLIF($4::text, '')
)
ON CONFLICT (google_subject) DO UPDATE SET
    email = EXCLUDED.email,
    display_name = COALESCE(EXCLUDED.display_name, users.display_name),
    avatar_url = COALESCE(EXCLUDED.avatar_url, users.avatar_url),
    updated_at = now()
RETURNING id::text
`

type UpsertGoogleUserParams struct {
	GoogleSubject string
	Email         string
	DisplayName   string
	AvatarUrl     string
}

func (q *Queries) UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertGoogleUser,
		arg.GoogleSubject,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
